subchart1:
  enabled: true
  replicaCount: 2
  
mongodb:
  enabled: false
  service:
    type: LoadBalancer
    port: 27017

wordpress:
  enabled: true
  replicaCount: 3
  wordpressUsername: kylian
  wordpressPassword: hallo123

grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  admin:
    user: "kylian"
    password: "hallo123"

elasticsearch:
  enabled: false
  service:
    type: LoadBalancer
    port: 9200

joomla:
  enabled: false
  service:
    type: LoadBalancer
    port: 8080