replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: LoadBalancer
  port: 8080

autoscaling:
  enabled: false

nginx:
  conf:
    message: "De subchart werkt gewoon! :)"
